trigger:
  branches:
    include:
    - develop
    - main
  paths:
    include:
    - infra/azure/*
    
name: Build-Template.Infra.$(BuildID)

jobs:
- job: 'Clean_and_Publish_Terraform'
  displayName: 'Publish Terraform for Infra'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: Bash@3
    displayName: Clean folder for publication
    inputs:
      targetType: inline
      script: >-
        #!/bin/bash
        # init
        
        rm dev.tfvars
        rm -rf '.terraform/'
      
      workingDirectory: infra/azure
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Terraform Pipeline Artifact'
    inputs:
      targetPath: infra/azure
      artifact: infra-azure
