# Explicitly set none for repositry trigger
trigger:
- none

resources:
  pipelines:
  - pipeline: "resourceBuild"  # Name of the pipeline resource
    source: "Build-Template-Databricks" # Name of the triggering pipeline
    trigger: 
      branches:
      - develop
      - main
      - release/*
      - hotfix/*
      - feature/*

stages:
- stage: Dev
  displayName: Developpement
  condition: or(eq(variables['Build.SourceBranch'],'refs/heads/develop'), startsWith(variables['Build.SourceBranch'],'refs/heads/feature'), startsWith(variables['Build.SourceBranch'],'refs/heads/fix'))

  variables:
  - group: 'Infra-Dev'
  - group: 'Infra-Common'

  jobs:
  - template: release-terraform-stage-template.yml
    parameters: 
      ServiceConnection: 'CONNECTION-DEV'
      PoolName: 'POOL-DEV'
      PipelineResourceName: 'resourceBuild'
      EnvironmentName: Develop
      ArtifactName: databricks
      TerraformKey: $(TerraformDatabricksKey)

- stage: Prod
  displayName: Production
  condition: eq(variables['Build.SourceBranch'],'refs/heads/main')

  variables:
  - group: 'Infra-Prod'
  - group: 'Infra-Common'

  jobs:
  - template: release-terraform-stage-template.yml
    parameters: 
      ServiceConnection: 'CONNECTION-PRD'
      PoolName: 'POOL-PRD'
      PipelineResourceName: 'resourceBuild'
      EnvironmentName: Production
      ArtifactName: databricks
      TerraformKey: $(TerraformDatabricksKey)